### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by Sihao** [yu-lab-vt/AQuA2#1]
Hello, 

The links in the 'Getting started' section seem to have expired.

**Comment by XuelongMi** [comment]
Thank you for reminding me. Now the links are fixed

**Comment by XuelongMi** [comment]
Apologies for not realizing the expiration date for sharing outside on OneDrive; I've now transitioned to using Google Drive for document sharing.

**Comment by Sihao** [comment]
Thank you!
