### ISSUE TITLE
fh.needTemp.Value and  fh.needSpa.Value in aqua_cmd_batch.m

### ISSUE THREAD

**Issue by Sihao** [yu-lab-vt/AQuA2#3]
https://github.com/yu-lab-vt/AQuA2/blob/22252dab7b15fe4028abd8d4e1a3715c059dc3b5/aqua_cmd_batch.m#L157
https://github.com/yu-lab-vt/AQuA2/blob/22252dab7b15fe4028abd8d4e1a3715c059dc3b5/aqua_cmd_batch.m#L159
https://github.com/yu-lab-vt/AQuA2/blob/22252dab7b15fe4028abd8d4e1a3715c059dc3b5/aqua_cmd_batch.m#L176
https://github.com/yu-lab-vt/AQuA2/blob/22252dab7b15fe4028abd8d4e1a3715c059dc3b5/aqua_cmd_batch.m#L178

These seem to be undefined. 
Works for me if I change to
`opts.needTemp` and `opts.needSpa`

**Comment by XuelongMi** [comment]
Thank you for your reminder! That's indeed my mistake. Now the issues have been fixed in aqua_cmd_batch.m.
