### ISSUE TITLE
no network feature detection in aqua_cmd_batch for AQuA2

### ISSUE THREAD

**Issue by kaitlin-s** [yu-lab-vt/AQuA2#5]
Hi! I want to extract the network features while working in batch mode in AQuA2. In the batch parameters I selected this feature but when I get the feature table only the basic features and propagation metrics are there, no networks. 

Thanks for your help!

Kaitlin

**Comment by XuelongMi** [comment]
Thank you for letting us know about this oversight. We have now updated the `aqua_cmd_batch.m` file to include the extraction of network features. By default, this feature is enabled, and you can adjust it on line 20.
