### ISSUE TITLE
Spatial Segmentation Error

### ISSUE THREAD

**Issue by NisanSele** [yu-lab-vt/AQuA2#6]
Hi,

I'm trying to use the AQuA2 package with Matlab R2024a, and I am getting this error at the spatial segmentation step:

Unrecognized function or variable 'DTW_Edge_input'.

Error in evt.spgtw (line 141)
    initialCut0 = DTW_Edge_input(mean(distMatrix,3))+1;

Error in evt.se2evt (line 10)
    [dlyMaps,t_scl,minTs,spLst,cx] = evt.spgtw(dF0,seMap0,seSel,superVoxels,major0,opts);

Error in evt.se2evtTop (line 63)
         [evtRecon,evtL,dlyMaps,nEvt0,svLabel] = evt.se2evt(...

Error in ui.detect.evtRun (line 26)
    [riseLst1,datR1,evtLst1,~] = evt.se2evtTop(dF1,seLst1,subEvtLst1,seLabel1,majorInfo1,opts,ff);

Error in ui.detect.flow (line 41)
            ui.detect.evtRun([],[],f);
 
Error using appdesservices.internal.interfaces.model.AbstractModel/executeUserCallback (line 282)
Error while evaluating Button PrivateButtonPushedFcn.

When I try to ask Matlab if it can locate the DTW_Edge_input function by using the which command, it says the function is not found. When I disable the spatial segmentation step, the rest of the package seems to run fine, but I wanted to reach out to see if there might be a fix for this.

Thanks!

**Comment by XuelongMi** [comment]
Hi NisanSele,

Which operating system are you using? The code is located in 'AQuA2/BILCO/', and it's a MEX file compiled from C++ in MATLAB. I have prepared the files for Windows, Mac, and Linux systems, but they are all 64-bit. Maybe your system is 32-bit? Please let me know your operating system so I can help locate the issue.

Best Wishes,
Xuelong Mi

**Comment by NisanSele** [comment]
Hi,

I'm using a MacBook Pro (macOS 14.1.2) with an M2 Max chip--my understanding is that all Apple chips are 64 bit, but maybe the issue is arising because it's an Apple silicone chip and not an Intel chip?

Thank you,
Nisan Sele

**Comment by XuelongMi** [comment]
MEX files are compiled from C++ code to be used within MATLAB. The file extensions are platform-specific: '.mexw64' for Windows, '.mexmaci64' for Mac, and '.mexa64' for Linux. Currently, I am unable to reproduce the issue.

Here are some possible solutions:

1. Try to compile the MEX file on your computer:
- - Enter 'AQuA2/BILCO/' folder in MATLAB.
- - Type the following commands in the MATLAB Command Window:
`mex BILCOMex.cpp`
`mex DTW_Edge_input.cpp`
- - These commands will compile the C++ code into MEX files suitable for your system. Then, you can try running AQuA2 again.
2. Use our Fiji version available at: https://github.com/yu-lab-vt/AQuA2-Fiji
3. Try using another computer with a Windows system

**Comment by NisanSele** [comment]
Compiling the MEX file worked! Thanks so much!

**Comment by XuelongMi** [comment]
Hi NisanSele, 

Could you please attach the compiled MEX files (the two most recently modified files in the BILCO folder) to this issue? This would help others encountering the same problem to find solutions more easily. In addition, if they have a different postfix from 'mexw64', 'mexmaci64', and 'mexa64', I will add them to GitHub.

Best wishes, 
Xuelong

**Comment by NisanSele** [comment]
Here you go! Thanks for the help again!

[AQuA2_compiled.zip](https://github.com/user-attachments/files/15774437/AQuA2_compiled.zip)
