### ISSUE TITLE
landmark feature from AQuA in AQuA2?

### ISSUE THREAD

**Issue by kaitlin-s** [yu-lab-vt/AQuA2#7]
Hi! I'm wondering if its possible to include the landmark feature from AQuA in AQuA2? 

Thanks, 

Kaitlin

**Comment by XuelongMi** [comment]
Hi, Kaitlin,

AQuA2 has included the landmark feature. To enable it, in the final step of GUI ("feature extraction" step), the "Network features" should be selected.
![image](https://github.com/user-attachments/assets/19349a62-189e-49a2-b2b9-3932dc809a75)

**Comment by kaitlin-s** [comment]
Hi Xuelong, 

Thanks for your reply! I was wondering mainly about these features from AQuA, when I select "Network features" I still don't see these: 

![Screenshot (145)](https://github.com/user-attachments/assets/4baa3146-8261-4080-b2e2-b1f760e9a547)

In AQuA2 I only see Landmark - event average distance and Landmark - event minimum distance as landmark features.

Thanks for your help, 

Kaitlin

**Comment by XuelongMi** [comment]
Hi kaitlin,

I've modified the code and uploaded it to Github. Now the newest version could satisfy your demand.
Previously, to make AQuA2 compatible with 3D data, I simplified that feature. Now for 2D data, landmark features will use the code from AQuA.

**Comment by XuelongMi** [comment]
Sorry, there is one bug about landmark features, and the newest code repair it.
Last month when I call the 2D landmark analysis back, the input variables are not correct and will make the landmark features wrong
